// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPZS1sjjpYe1viJOigyjFnwBn47fKd2Do',
    appId: '1:273325396141:web:c26fbef4ff7ee3e6b17624',
    messagingSenderId: '273325396141',
    projectId: 'orbit-talk-73aad',
    authDomain: 'orbit-talk-73aad.firebaseapp.com',
    storageBucket: 'orbit-talk-73aad.firebasestorage.app',
    measurementId: 'G-3TWMSTMJTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAV0EoFjSw9woTbfzK67qqwkvnN1KPZog',
    appId: '1:273325396141:android:ff6ba4e55c36238ab17624',
    messagingSenderId: '273325396141',
    projectId: 'orbit-talk-73aad',
    storageBucket: 'orbit-talk-73aad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5mk29EG73I9PEIRCBeWFKBr12rg13OIs',
    appId: '1:273325396141:ios:2a4fb995e9b3939eb17624',
    messagingSenderId: '273325396141',
    projectId: 'orbit-talk-73aad',
    storageBucket: 'orbit-talk-73aad.firebasestorage.app',
    iosBundleId: 'com.crenno.orbit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5mk29EG73I9PEIRCBeWFKBr12rg13OIs',
    appId: '1:273325396141:ios:9b22f6106164cf59b17624',
    messagingSenderId: '273325396141',
    projectId: 'orbit-talk-73aad',
    storageBucket: 'orbit-talk-73aad.firebasestorage.app',
    iosBundleId: 'com.example.orbitPtt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPZS1sjjpYe1viJOigyjFnwBn47fKd2Do',
    appId: '1:273325396141:web:aa94163be7130b15b17624',
    messagingSenderId: '273325396141',
    projectId: 'orbit-talk-73aad',
    authDomain: 'orbit-talk-73aad.firebaseapp.com',
    storageBucket: 'orbit-talk-73aad.firebasestorage.app',
    measurementId: 'G-D3PF7JZ3JB',
  );
}
